development:
  bucket_name: gazeta_development
  access_key_id: 1RX1190JQBAV
  secret_access_key: RN2nBEFhYu8k5S3kVXtM
  persistent: false 

test:
  bucket_name: gazeta_test
  access_key_id: 1RX1190JQBAV
  secret_access_key: RN2nBEFhYu8k5S3kVXtM
  persistent: false 

production:
  bucket_name: gazeta
  access_key_id: 1RX1190JQBAV
  secret_access_key: RN2nBEFhYu8k5S3kVXtM
  persistent: false